### Cadastrar task
POST https://localhost:5001/api/task/create
Content-Type: application/json

{
    "NomeTask": "Ir no mercado",
    "DescricaoTask": "Comprar bolacha",
    "Prioridade": "Importante",
    "DataTask": "19/09"
}

### Listar todas as tasks
GET https://localhost:5001/api/task/list

### Buscar produto pelo id
GET https://localhost:5001/api/task/getbyid/1